global:
  scrape_interval: 10s
  evaluation_interval: 10s
  scrape_timeout: 10s

rule_files:
  - /etc/prometheus/alert.yml

scrape_configs:
  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:3016"]
  - job_name: "mongodb"
    static_configs:
      - targets: ["db-exporter:9216"]