groups:
  - name: DownAlert
    rules:
      - alert: "On api-gateway down"
        expr: up{job="api-gateway"} < 1
        for: 15s
      - alert: "On mongodb down"
        expr: up{job="mongodb"} < 1
        for: 5s