name: 'coverage'
on:
    pull_request:
        branches:
            - master
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Install dependencies
            run: npm install
          - name: Run Jest
            run: npm test -- --coverage
          - name: Generate coverage report
            uses: ArtiomTr/jest-coverage-report-action@v2
