name: Node.js

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '.'

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: "package-lock.json"

    - run: npm ci --legacy-peer-deps
    - run: npm run build --if-present
    # Replace the "npm test" command with "docker-compose run app npm test" to run your tests against the MongoDB container
    - run: docker-compose run mongodb npm test --coverage

    
    - name: Jest coverage report
      uses: ArtiomTr/jest-coverage-report-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: ESLinter
      run: npm run lint
      working-directory: .
