name: Okteto Service Status
on:
  schedule:
    - cron: '0 * * * *' # run every hour
  push:
    branches:
      - main
jobs:
  check-service:
    runs-on: ubuntu-latest
    steps:
      - name: Set up cURL
        run: sudo apt-get install -y curl
      - name: Get service status
        id: service-status
        run: |
          if curl --output /dev/null --silent --head --fail "https://api-gateway-jeroene2000.cloud.okteto.net"; then
            echo "Service is up and running"
            echo "::set-output name=status::up"
          else
            echo "Service is not running"
            echo "::set-output name=status::down"
          fi
      - name: Generate badge
        uses: peaceiris/actions-badge@v2
        with:
          style: flat-square
          label: ${{ github.repository }} status
          message: ${{ steps.service-status.outputs.status }}
          color: ${{ steps.service-status.outputs.status == 'up' && '#4c1' || '#f00' }}
        id: status-badge
      - name: Update README
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update service status badge
          commit_options: '--no-verify'
          repository: ${{ github.repository }}
          branch: ${{ github.ref }}
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
          file_pattern: README.md
          file_content: |
            | devops-Webs5-2223-Jeroen-Elst-Quinn-Diepstraten status | ![Status](${{ steps.status-badge.outputs.badge }}) |
