name: Update Status Badges

on:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  update-readme-with-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/update-readme-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          file: README.md
          updater: github
          content: |
            | Service          | Status                                                                                                                       |
            | ---------------- | ---------------------------------------------------------------------------------------------------------------------------- |
            | GATEWAY          | [![okteto-main-publish](https://img.shields.io/endpoint?url=https://status.octo-prod.jeroene2000.cloud.okteto.net/gateway.json)](https://status.octo-prod.jeroene2000.cloud.okteto.net/gateway) |
            | AUTH_SERVICE     | [![okteto-main-publish](https://img.shields.io/endpoint?url=https://status.octo-prod.jeroene2000.cloud.okteto.net/auth-service.json)](https://status.octo-prod.jeroene2000.cloud.okteto.net/auth-service) |
            | EXTERNAL_SERVICE | [![okteto-main-publish](https://img.shields.io/endpoint?url=https://status.octo-prod.jeroene2000.cloud.okteto.net/external-service.json)](https://status.octo-prod.jeroene2000.cloud.okteto.net/external-service) |
            | TARGET_SERVICE   | [![okteto-main-publish](https://img.shields.io/endpoint?url=https://status.octo-prod.jeroene2000.cloud.okteto.net/target-service.json)](https://status.octo-prod.jeroene2000.cloud.okteto.net/target-service) |
            | SCORE_SERVICE    | [![okteto-main-publish](https://img.shields.io/endpoint?url=https://status.octo-prod.jeroene2000.cloud.okteto.net/score-service.json)](https://status.octo-prod.jeroene2000.cloud.okteto.net/score-service) |
            | RABBITMQ         | [![okteto-main-publish](https://img.shields.io/endpoint?url=https://status.octo-prod.jeroene2000.cloud.okteto.net/rabbitmq.json)](https://status.octo-prod.jeroene2000.cloud.okteto.net/rabbitmq) |
            | Grafana          | [![okteto-main-publish](https://img.shields.io/endpoint?url=https://status.octo-prod.jeroene2000.cloud.okteto.net/grafana.json)](https://status.octo-prod.jeroene2000.cloud.okteto.net/grafana) |
            | Prometheus       | [![okteto-main-publish](https://img.shields.io/endpoint?url=https://status.octo-prod.jeroene2000.cloud.okteto.net/prometheus.json)](https://status.octo-prod.jeroene2000.cloud.okteto.net/prometheus) | 