on:
  pull_request:
    branches:
      - main

name: okteto-main-publish

jobs:
  devflow:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@main

    - name: context
      uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: "Activate Namespace"
      uses: okteto/namespace@latest
      with:
        name: jeroene2000

    - name: "Trigger the pipeline"
      uses: okteto/pipeline@latest
      with:
        name: pr-${{ github.event.number }}
        timeout: 15m
        skipIfExists: true
        variables: |
          DB_HOST=mysql,CONFIG_PATH=/tmp/config.yaml,
          EXTERNESERVICE_DB_CONNECTION=mongodb://mongodb:27017/photoprestiges,
          TARGETSERVICE_DB_CONNECTION=mongodb://mongodb:27017/target,
          SCORESERVICE_DB_CONNECTION=mongodb://mongodb:27017/score,
          AUTHENTICATIONSERVICE_DB_CONNECTION=mongodb://mongodb:27017/auth,
          JWT_SECRET=tasmanianDevil,
          OPAQUE_TOKEN=1234567890,
          TESTING=true,
          TARGET_SERVICE_URL=http://targetservice:3012,
          SCORE_SERVICE_URL=http://scoreservice:3038,
          EXTERNAL_SERVICE_URL=http://externalservice:3039,
          AUTHENTICATION_SERVICE_URL=http://authenticationservice:3015,
          MICROSERVICE_BASE_URL=http://api-gateway:3016,
          TARGET_SERVICE_PORT=3012,
          SCORE_SERVICE_PORT=3038,
          EXTERNAL_SERVICE_PORT=3039,
          AUTHENTICATION_SERVICE_PORT=3015,
          MICROSERVICE_BASE_PORT=3016
